# Generated by Django 6.0.3 on 2026-04-05 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=255)),
                ('name_ar', models.CharField(max_length=255)),
                ('description_en', models.TextField(blank=True, null=True)),
                ('description_ar', models.TextField(blank=True, null=True)),
                ('causes_en', models.TextField(blank=True, null=True)),
                ('causes_ar', models.TextField(blank=True, null=True)),
                ('treatment_en', models.TextField(blank=True, null=True)),
                ('treatment_ar', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'diseases',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('role', models.CharField(choices=[('user', 'user'), ('admin', 'admin'), ('expert', 'expert')], default='user', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_type', models.CharField(choices=[('image', 'image'), ('text', 'text')], max_length=10)),
                ('image_url', models.TextField(blank=True, null=True)),
                ('text_input', models.TextField(blank=True, null=True)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('disease', models.ForeignKey(db_column='disease_id', on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to='api.disease')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to='api.user')),
            ],
            options={
                'db_table': 'diagnoses',
                'constraints': [models.CheckConstraint(condition=models.Q(('input_type__in', ['image', 'text'])), name='diagnoses_input_type_check')],
            },
        ),
    ]
