# Generated by Django 6.0.3 on 2026-04-05 17:28

import django.db.models.deletion
from django.db import migrations, models


def assign_default_plant_for_diseases(apps, schema_editor):
    Plant = apps.get_model("api", "Plant")
    Disease = apps.get_model("api", "Disease")
    plant = Plant.objects.first()
    if plant is None:
        plant = Plant.objects.create(name_en="Unassigned", name_ar="غير مصنف")
    Disease.objects.filter(plant_id__isnull=True).update(plant_id=plant.pk)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial_domain_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=255)),
                ('name_ar', models.CharField(max_length=255)),
                ('description_en', models.TextField(blank=True, null=True)),
                ('description_ar', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'plants',
            },
        ),
        migrations.CreateModel(
            name='AILog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_data', models.TextField(blank=True, null=True)),
                ('predicted_disease', models.CharField(blank=True, max_length=255, null=True)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('diagnosis', models.ForeignKey(blank=True, db_column='diagnosis_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_logs', to='api.diagnosis')),
            ],
            options={
                'db_table': 'ai_logs',
            },
        ),
        migrations.AddField(
            model_name='disease',
            name='plant',
            field=models.ForeignKey(blank=True, db_column='plant_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='diseases', to='api.plant'),
        ),
        migrations.RunPython(assign_default_plant_for_diseases, noop_reverse),
        migrations.AlterField(
            model_name='disease',
            name='plant',
            field=models.ForeignKey(db_column='plant_id', on_delete=django.db.models.deletion.PROTECT, related_name='diseases', to='api.plant'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('diagnosis', models.ForeignKey(db_column='diagnosis_id', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='api.diagnosis')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='api.user')),
            ],
            options={
                'db_table': 'reviews',
            },
        ),
    ]
