"""
Generate Excel workbook with all test results.
Requires: pip install openpyxl

Usage:
    python generate_excel_report.py
"""

from pathlib import Path
from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from openpyxl.utils import get_column_letter

# Test data
VISION_TESTS = [
    ("TC-1", "Artificial", "Artificial image of a micro shoot for a healthy lemon tree branch.", "Healthy", "Witch Boom", "Fail"),
    ("TC-2", "Artificial", "Artificial image of a big lemon tree with witch broom disease symptoms.", "Witch Boom", "Witch Boom", "Pass"),
    ("TC-3", "Artificial", "Artificial image of a bunch of mango trees.", "Unknown", "Witch Boom", "Fail"),
    ("TC-4", "Available", "Image for part of a healthy lemon tree from a public dataset.", "Healthy", "Healthy", "Pass"),
    ("TC-5", "Available", "Image for part of a lemon tree diseased by witch broom from a public dataset.", "Witch Boom", "Witch Boom", "Pass"),
    ("TC-6", "Available", "Image of a cloudy sky without any trees.", "Unknown", "Unknown", "Pass"),
    ("TC-7", "Available", "Image for micro shoot for lemon branches with rot foot disease symptoms from a public dataset.", "Unknown", "Unknown", "Pass"),
    ("TC-8", "Available", "Blurred micro shot of a lemon tree's healthy branches.", "Unknown", "Unknown", "Pass"),
    ("TC-9", "Real", "Real image of a whole healthy lemon tree.", "Healthy", "Witch Boom", "Fail"),
    ("TC-10", "Real", "Real images taken by Dr. Abdullah AL-Sadi For part of a lemon tree with clear witch broom disease symptoms.", "Witch Boom", "Witch Boom", "Pass"),
]

TEXT_TESTS = [
    ("TC-11", "Artificial", "Artificially created description for a healthy lemon plant.", "Healthy", "Healthy", "Pass"),
    ("TC-12", "Artificial", "Artificially created description for a lemon plant diseased with witch broom.", "Witch Boom", "Witch Boom", "Pass"),
    ("TC-13", "Artificial", "Artificially created description for a lemon tree diseased with greening.", "Unknown", "Healthy", "Fail"),
    ("TC-14", "Available", "Description from a website for healthy lemon plant leaves.", "Healthy", "Healthy", "Pass"),
    ("TC-15", "Available", "Description from a website for lemon witch broom disease symptoms.", "Witch Boom", "Healthy", "Fail"),
    ("TC-16", "Available", "Description from a website for unhealthy lemon leaves.", "Unknown", "Witch Boom", "Fail"),
    ("TC-17", "Real", "Real description generated by us for a healthy lemon tree.", "Healthy", "Healthy", "Fail"),
    ("TC-18", "Real", "Real description generated by us for diseased witch broom lemon disease.", "Witch Boom", "Healthy", "Fail"),
    ("TC-19", "Real", "Real description generated by us for lemon plants with no clear symptoms.", "Unknown", "Healthy", "Fail"),
]

def style_header(cell):
    """Style header cell."""
    cell.font = Font(bold=True, color="FFFFFF", size=11)
    cell.fill = PatternFill(start_color="366092", end_color="366092", fill_type="solid")
    cell.alignment = Alignment(horizontal="center", vertical="center", wrap_text=True)

def style_pass_fail(cell, status):
    """Style Pass/Fail cell."""
    if status == "Pass":
        cell.fill = PatternFill(start_color="C6EFCE", end_color="C6EFCE", fill_type="solid")
        cell.font = Font(color="006100", bold=True)
    else:
        cell.fill = PatternFill(start_color="FFC7CE", end_color="FFC7CE", fill_type="solid")
        cell.font = Font(color="9C0006", bold=True)
    cell.alignment = Alignment(horizontal="center", vertical="center")

def style_border(cell):
    """Apply border to cell."""
    thin_border = Border(
        left=Side(style='thin'),
        right=Side(style='thin'),
        top=Side(style='thin'),
        bottom=Side(style='thin')
    )
    cell.border = thin_border

def create_test_sheet(ws, title, test_data):
    """Create a test results sheet."""
    ws.title = title
    
    # Headers
    headers = ["Test Case ID", "Data Type", "Input Description", "Expected Class", "Actual Class", "Status"]
    
    for col, header in enumerate(headers, 1):
        cell = ws.cell(row=1, column=col, value=header)
        style_header(cell)
    
    # Data rows
    for row_idx, test in enumerate(test_data, 2):
        for col_idx, value in enumerate(test, 1):
            cell = ws.cell(row=row_idx, column=col_idx, value=value)
            style_border(cell)
            
            if col_idx == 6:  # Status column
                style_pass_fail(cell, value)
            else:
                cell.alignment = Alignment(horizontal="left", vertical="center", wrap_text=True)
    
    # Adjust column widths
    ws.column_dimensions['A'].width = 12
    ws.column_dimensions['B'].width = 12
    ws.column_dimensions['C'].width = 50
    ws.column_dimensions['D'].width = 15
    ws.column_dimensions['E'].width = 15
    ws.column_dimensions['F'].width = 10
    
    # Set row heights
    ws.row_dimensions[1].height = 25
    for row in range(2, len(test_data) + 2):
        ws.row_dimensions[row].height = 40

def create_summary_sheet(wb):
    """Create summary sheet with statistics."""
    ws = wb.create_sheet("Summary", 0)
    ws.title = "Summary"
    
    # Title
    title_cell = ws.cell(row=1, column=1, value="SMART AGRI AI - Unit Test Results Summary")
    title_cell.font = Font(bold=True, size=14, color="FFFFFF")
    title_cell.fill = PatternFill(start_color="1F4E78", end_color="1F4E78", fill_type="solid")
    ws.merge_cells("A1:C1")
    
    # Overall Statistics
    row = 3
    ws.cell(row=row, column=1, value="Metric").font = Font(bold=True, size=11)
    ws.cell(row=row, column=2, value="Value").font = Font(bold=True, size=11)
    
    stats = [
        ("Total Tests", 19),
        ("Total Passed", 10),
        ("Total Failed", 9),
        ("Overall Pass Rate", "52.6%"),
        ("", ""),
        ("Vision Model Tests", 10),
        ("Vision Passed", 6),
        ("Vision Failed", 4),
        ("Vision Pass Rate", "60%"),
        ("", ""),
        ("Text Model Tests", 9),
        ("Text Passed", 4),
        ("Text Failed", 5),
        ("Text Pass Rate", "44.4%"),
    ]
    
    for stat, value in stats:
        row += 1
        if stat:
            ws.cell(row=row, column=1, value=stat).font = Font(bold=True)
            ws.cell(row=row, column=2, value=value).font = Font(size=11)
    
    # By Data Type
    row += 3
    ws.cell(row=row, column=1, value="Performance by Data Type").font = Font(bold=True, size=11)
    
    row += 1
    headers = ["Data Type", "Vision", "Text", "Combined"]
    for col, header in enumerate(headers, 1):
        cell = ws.cell(row=row, column=col, value=header)
        cell.font = Font(bold=True, color="FFFFFF")
        cell.fill = PatternFill(start_color="366092", end_color="366092", fill_type="solid")
    
    data_types = [
        ("Artificial", "1/3 (33%)", "2/3 (67%)", "50%"),
        ("Available", "5/6 (83%)", "1/3 (33%)", "67%"),
        ("Real", "1/1 (100%)", "1/3 (33%)", "50%"),
    ]
    
    for data_type, vision, text, combined in data_types:
        row += 1
        ws.cell(row=row, column=1, value=data_type)
        ws.cell(row=row, column=2, value=vision)
        ws.cell(row=row, column=3, value=text)
        ws.cell(row=row, column=4, value=combined)
    
    # By Classification
    row += 3
    ws.cell(row=row, column=1, value="Accuracy by Classification Class").font = Font(bold=True, size=11)
    
    row += 1
    headers = ["Class", "Vision", "Text", "Combined"]
    for col, header in enumerate(headers, 1):
        cell = ws.cell(row=row, column=col, value=header)
        cell.font = Font(bold=True, color="FFFFFF")
        cell.fill = PatternFill(start_color="366092", end_color="366092", fill_type="solid")
    
    classes = [
        ("Healthy", "67%", "100%", "83%"),
        ("Witch Boom", "75%", "33%", "57%"),
        ("Unknown", "33%", "0%", "17%"),
    ]
    
    for class_name, vision, text, combined in classes:
        row += 1
        ws.cell(row=row, column=1, value=class_name)
        ws.cell(row=row, column=2, value=vision)
        ws.cell(row=row, column=3, value=text)
        ws.cell(row=row, column=4, value=combined)
    
    ws.column_dimensions['A'].width = 25
    ws.column_dimensions['B'].width = 15
    ws.column_dimensions['C'].width = 15
    ws.column_dimensions['D'].width = 15

def main():
    """Generate Excel workbook."""
    wb = Workbook()
    wb.remove(wb.active)  # Remove default sheet
    
    # Create summary sheet first
    create_summary_sheet(wb)
    
    # Create vision and text sheets
    vision_sheet = wb.create_sheet("Vision Tests")
    create_test_sheet(vision_sheet, "Vision Tests", VISION_TESTS)
    
    text_sheet = wb.create_sheet("Text Tests")
    create_test_sheet(text_sheet, "Text Tests", TEXT_TESTS)
    
    # Save file
    output_path = Path(__file__).parent / "Test_Results.xlsx"
    wb.save(output_path)
    print(f"✓ Excel file created: {output_path}")
    print(f"  - Summary sheet with statistics")
    print(f"  - Vision Tests sheet (TC-1 to TC-10)")
    print(f"  - Text Tests sheet (TC-11 to TC-19)")

if __name__ == "__main__":
    try:
        main()
    except ImportError:
        print("Error: openpyxl is not installed")
        print("Install it with: pip install openpyxl")
